version: '3.8'

# Use "docker-compose up --build"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-db
    environment:
      SA_PASSWORD: "Strong@Passw0rd-H92q6DmeV5SWS2LTy161f"
      ACCEPT_EULA: "Y"
      MSSQL_DATABASE: "DatabaseName-Dev"
      MSSQL_USER: "user-name-strong"           
      MSSQL_PASSWORD: "UserPassw0rd-va7zmJn5MGM3iE8Z32h0i"  
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

volumes:
  sqlserver_data:
