# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - SchedulingSystem

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Install EF Core tools
        run: dotnet tool install --global dotnet-ef

      - name: Build with dotnet
        run: dotnet build API/API.csproj --configuration Release

      - name: Update Database
        run: dotnet ef database update --project API/API.csproj --configuration Release

      - name: dotnet publish
        run: dotnet publish API/API.csproj -c Release -o myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
            client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_70E52F1B079245608B07A3FB93BB8324 }}
            tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_76087CEECD6343F3AD0280B3F8F62D4E }}
            subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_410D5E28BACF46BA9B5FB6117E31C1C9 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'SchedulingSystem'
          slot-name: 'Production'
          package: .
          


